@startuml

class RockPaperScissorsApp {
    +main(args: String[]): void
}

class Game {
    -Player player
    -Player computer
    -int playerScore
    -int computerScore
    -int rounds
    +play(): void
    -updateScore(result: String): void
    +determineWinner(humanChoice: ChoiceType, opponentChoice: ChoiceType): String
}

interface Player {
    #String name
    +makeChoice(): ChoiceType
    +getName(): String
}

class HumanPlayer {
    +makeChoice(): ChoiceType
}

class ComputerPlayer {
    +makeChoice(): ChoiceType
}

enum ChoiceType {
    ROCK
    PAPER
    SCISSORS
}

RockPaperScissorsApp --> Game
Game --> Player
Game --> HumanPlayer
Game --> ComputerPlayer
Player <|-- HumanPlayer
Player <|-- ComputerPlayer
Player --> ChoiceType


@enduml
